# snmptrapd configuration file
disableAuthorization yes

# Log SNMP traps to syslog
#logOption f /var/log/snmptrapd.log

# Community string to accept traps from (replace 'public' with your community string if needed)
authCommunity log,execute,net public
