# /etc/netplan/50-cloud-init.yaml
# Note: Activate with -- netplan apply
# old style
network:
  ethernets:
    ens2:
      dhcp4: no
      addresses:
        - 10.100.99.2/25
      gateway4: 10.100.99.1
      match:
        macaddress: "52:54:00:08:10:52"
      set-name: ens2
  version: 2
