#!/usr/bin/env bash

addresses=(10.100.199.10 10.100.99.10 10.192.168.2)

for address in "${addresses[@]}"; do
	sshpass '-pcisco' \
		scp -o StrictHostKeyChecking=accept-new \
		~/scripts/multicast/mcast_generator.py \
		cisco@"$address":~ >/dev/null 2>&1
	echo "$address done"
done
